config/routes.rb
AroundTheWorld::Application.routes.draw do
  get "events/index"
  #Static Pages
  root 'events#index'

  resources :events
  match '/events/:id/orders', to: 'events#event_orders', via: 'get', as: 'event_orders'
  match '/events/:id/vendors', to: 'events#event_vendors', via: 'get', as: 'event_vendors'
  match '/events/:id/analytics', to: 'events#event_analytics', via: 'get', as: 'event_analytics'

  resources :users
  match '/signup', to: 'users#new', via: 'get'

  resources :sessions, only: [:new, :create, :destroy]
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

  resources :vendors
  match '/vendors/:id/history', to: 'vendors#history', via: 'get'

  resources :customers do
    member do
      get 'place_order'
    end
  end

  resources :orders do
    member do
      get 'open'
      get 'backtrack'
    end
  end

  resources :order_items

  resources :analytics

  match '/home', to: 'static_pages#home', via: 'get'
end

app/models/customer.rb
class Customer < ActiveRecord::Base
	searchkick word_start: [:name]

	#relationships
	has_many :orders, dependent: :destroy
	has_many :order_items, dependent: :destroy
	belongs_to :user

	#validations
	validates :name, presence: true

	#scopes
	scope :recently, -> {order("created_at DESC")}

	def calculate_total
		total = 0.0

		self.order_items.orderless.complete.each do |order_item|
			if order_item.vendor.tax
				total = total + 1.0875 * order_item.price * order_item.quantity
			else
				total = total+order_item.price*order_item.quantity
			end
		end

		return total
	end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
	respond_to :html, :json

	def place_order
		@customer = Customer.find(params[:id])
		@order_items = @customer.order_items.recently
		@event = Event.find_by_id(params[:event_id])
		respond_to do |format|
			format.js
		end
	end

	def index
		@customers = Customer.recent_ones_first

		if signed_in?
			if params[:query].present?
	      @customers = @customers.search(params[:query], operator: "or", fields: [:name])
	    else
	      @customers = @customers.paginate(page: params[:page], per_page: 20)
			end
		else
			redirect_to "/home"
			flash[:notice]="Sign in below!"
		end
	end

	def create
		@customer = Customer.new(customer_params)
		@customer.user_id = current_user.id
		@saved = @customer.save
		@event = Event.find_by_id(params[:event_id])
		@order_items = @customer.order_items.recently

		respond_to do |format|
			format.js
		end
	end

	def edit
		@customer = Customer.find(params[:id])
	end

	def update
		@customer = Customer.find(params[:id])
		@updated = @customer.update_attributes(customer_params)
		respond_to do |format|
			format.js
		end
	end

	def destroy
		@customer = Customer.find(params[:id])
		@destroyed = @customer.destroy
		respond_to do |format|
			format.js
		end
	end

	private

		def customer_params
			params.require(:customer).permit(:name, :email, :user_id)
		end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_customer.html.erb
<div class='sexy-divider sexy-divider-<%= customer.id %>'>
	<%= link_to raw("<i class='fa fa-cog'></i>"), edit_customer_path(customer), remote: true, class: 'edit-customer-link' %> 
</div>

<% if @event %>
	<%= link_to place_order_customer_path(customer, event_id: @event.id), remote: true, class: "customer customer-#{customer.id}" do %>
		<i class='fa fa-user'></i>
		<span><%= customer.name %></span>
	<% end %>
<% else %>
	<%= link_to place_order_customer_path(customer, event_id: request.original_url.split('/')[4]), remote: true, class: "customer customer-#{customer.id}" do %>
		<i class='fa fa-user'></i>
		<span><%= customer.name %></span>
	<% end %>
<% end %>

app/views/customers/_customer_list.html.erb
<div class="sexy-divider"></div>

<!-- search customers by name -->

<%= form_tag event_path(@event), class: 'search-customers-form', method: :get, remote: true do %>
  <%= text_field_tag :query, params[:query], placeholder: "Search by customer name", id: "customer-search-field", class: 'default-input', autofocus: true %>
<% end %>

<div id='customer-list'>
	<%= render @customers %>

	<%= will_paginate @customers %>
</div>

<div class='modal-overlay' id='customer-overlay'>
	<%= simple_form_for Customer.new, remote: true do |f| %>
		<i class='fa fa-times exit-customer-form'></i>

		<h1>Create New Customer</h1>

		<div class="sexy-divider"></div>

		<%= hidden_field_tag :event_id, @event.id %>
		<%= f.input :name, placeholder: 'Customer Name', label: false, input_html: {class: 'default-input'} %>
		<%= f.input :email, placeholder: 'Customer Email', label: false, input_html: {class: 'default-input'}, required: false %>

		<%= f.submit "Create Customer", class: 'blue-button' %>
	<% end %>
</div>

app/views/customers/_edit.html.erb
<div class='modal-overlay' id='edit-customer-overlay'>
	<%= simple_form_for @customer, remote: true do |f| %>
		<i class='fa fa-times exit-form'></i>

		<h1>Update Customer</h1>

		<div class="sexy-divider"></div>

		<%= f.input :name, placeholder: 'Customer Name', label: false, input_html: {class: 'default-input'} %>
		<%= f.input :email, placeholder: 'Customer Email', label: false, input_html: {class: 'default-input'} %>

		<%= f.submit "Update Customer", class: 'blue-button' %>
	<% end %>

	<div class="modal-overlay-footer">
		<%= link_to 'delete customer', @customer, remote: true, method: :delete, data: {confirm: "Sure you want to delete #{@customer.name}?"}, class: 'delete-customer-link' %>
	</div>
</div>

app/views/customers/_place_order.html.erb
<div class="place-order place-order-<%= @customer.id %>">
	<div class='sexy-divider'></div>

	<div class="order-vendor-list">
		<% @event.vendors.alphabetical.each_slice(4) do |slice| %>
			<div class='sexy-divider'></div>

			<div class="vendor-slice">
				<% slice.each do |vendor| %>
					<%= simple_form_for OrderItem.new, remote: true do |f| %>
						<%= f.hidden_field :vendor_id, value: vendor.id %>
						<%= f.hidden_field :customer_id, value: @customer.id %>

						<%= button_tag(type: 'submit', class: 'order-vendor') do %>
							<%= vendor.name %>
						<% end %>
					<% end %>
				<% end %>
				
				<div style="clear:both;"></div>
			</div>
		<% end %>

		<div style='clear:both;'></div>

		<div class='sexy-divider'></div>
	</div>

	<div class='order-item-list'>
		<div class="checkout-total">
			<%= number_to_currency(@customer.calculate_total, precision: (@customer.calculate_total.round == @customer.calculate_total) ? 0 : 2) %>
		</div>

		<%= simple_form_for Order.new, remote: true do |f| %>
			<%= f.hidden_field :event_id, value: @event.id %>
			<%= f.hidden_field :customer_id, value: @customer.id %>
			
			<%= button_tag(type: 'submit', class: 'blue-button checkout-button') do %>
				Checkout
			<% end %>
		<% end %>

		<%= render @order_items.orderless %>
	</div>

	<div style='clear:both;'></div>
</div>

app/views/customers/create.js.erb
<% if @saved %>
	//add new customer
	$("#customer-overlay").hide();
	$("#new_customer")[0].reset();
	$("#customer-list").prepend("<%= j render @customer %>");
	$(".customer-<%= @customer.id %>").after("<%= j render 'customers/place_order' %>");
	$('.customer-<%= @customer.id %>').addClass('selected');
<% end %>

app/views/customers/destroy.js.erb
<% if @destroyed %>
	//remove modal and customer
	$("#edit-customer-overlay").remove();
	$(".sexy-divider-<%= @customer.id %>").remove();
	$(".customer-<%= @customer.id %>").remove();

	if($(".place-order-<%= @customer.id %>")[0]){
		$(".place-order-<%= @customer.id %>").remove();
	}
<% end %>

app/views/customers/edit.js.erb
//load form to edit customer
$("#dashboard-container").prepend("<%= j render 'customers/edit' %>");
$("#edit-customer-overlay #customer_name").focus();

app/views/customers/index.html.erb
<% content_for :dashboard_content do %>
<div id="customer-container">
	<!-- search customers by first name, last name, email, or phone -->

	<%= form_tag customers_path, method: :get do %>
	  <%= text_field_tag :query, params[:query], placeholder: "Search by name", id: "search-field" %>
	<% end %>

	<%= link_to "+ Customer", "#", remote: true, id: "create-customer-btn" %>

	<%= simple_form_for Customer.new, remote: true, html: {id: "customer-form"} do |f| %>
		<%= f.input :name, label: false, input_html: {placeholder: "Name", id: "name-field"} %>
		<%= f.input :email, label: false, input_html: {placeholder: "Email", id: "email-field"} %>
		<%= f.submit "submit", style: "visibility: hidden;" %>
	<% end %>

	<div style="clear:both;"></div>

	<div id="new-customer-list">
	</div>

	<div id="customer-list">
		<%= render @customers %>
	</div>

	<%= will_paginate @orders %>
</div>

<script>
$(document).ready(function(){
	$("#create-customer-btn").click(function(){
		$("#search-field").hide();
		$("#customer-form").show();
		$("#name-field").focus();
	});

	$(".customer-name, .customer-email").click(function(){
		$(this).children(".best_in_place").click();
	});

	$("#search-field").focus();
});
</script>
<% end %>

app/views/customers/place_order.js.erb
if($('.place-order-<%= @customer.id %>')[0]){
	//return to normal state
	$(".place-order").remove();
	$("#customer-list .selected").removeClass('selected');
} else{
	//show form to place order
	if($(".place-order")[0]){
		$(".place-order").remove();
	}

	if($("#customer-list .selected")[0]){
		$("#customer-list .selected").removeClass('selected');
	}

	$(".customer-<%= @customer.id %>").after("<%= j render 'customers/place_order' %>");
	$(".customer-<%= @customer.id %>").addClass("selected");
}

app/views/customers/update.js.erb
<% if @updated %>
	//remove modal to edit customer
	$("#edit-customer-overlay").remove();
	//replace customer name
	$(".customer-<%= @customer.id %> span").html("<%= @customer.name %>");
<% end %>