config/routes.rb
AroundTheWorld::Application.routes.draw do
  get "events/index"
  #Static Pages
  root 'events#index'

  resources :events
  match '/events/:id/orders', to: 'events#event_orders', via: 'get', as: 'event_orders'
  match '/events/:id/vendors', to: 'events#event_vendors', via: 'get', as: 'event_vendors'
  match '/events/:id/analytics', to: 'events#event_analytics', via: 'get', as: 'event_analytics'

  resources :users
  match '/signup', to: 'users#new', via: 'get'

  resources :sessions, only: [:new, :create, :destroy]
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

  resources :vendors
  match '/vendors/:id/history', to: 'vendors#history', via: 'get'

  resources :customers do
    member do
      get 'place_order'
    end
  end

  resources :orders do
    member do
      get 'open'
      get 'backtrack'
    end
  end

  resources :order_items

  resources :analytics

  match '/home', to: 'static_pages#home', via: 'get'
end

app/models/order.rb
class Order < ActiveRecord::Base

	#validations
	validates :customer_id, presence: true
	validates :event_id, presence: true

	#relationships
	has_many :order_items, dependent: :destroy
	belongs_to :customer
	belongs_to :user
	belongs_to :event

	#scopes
	scope :recently, -> {order('created_at DESC')}


  def recalculate_total_price
  	total = 0.0

		self.order_items.complete.each do |order_item|
			if order_item.vendor.tax
				total = total + 1.0875 * order_item.price * order_item.quantity
			else
				total = total+order_item.price*order_item.quantity
			end
		end

		self.total = total
		save!
	end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
	def backtrack
		@order = Order.find(params[:id])
		@customer = @order.customer
		@event = @order.event
		@order_items = @order.order_items
		@order_items.update_all(order_id:nil)
		@destroyed = @order.destroy

		respond_to do |format|
			format.js
		end
	end

	def open
		@order = Order.find(params[:id])
		@event = @order.event
		@customer = @order.customer
		@order_items = @order.order_items.recently
	end

	def index
		@orders = Order.recent_ones_first.paginate(page: params[:page], per_page: 10)
	end

	def show
		@order = Order.find(params[:id])
		@order_items = @order.order_items
	end

	def create
		@order = Order.new(order_params)
		@order.total = @order.customer.calculate_total
		@saved = @order.save

		@customer = @order.customer

		#update order id of all orderless order items
		@customer.order_items.orderless.complete.update_all(order_id:@order.id)

		respond_to do |format|
			format.js
		end
	end

	def edit
		@order = Order.find(params[:id])
	end

	def update
		@order = Order.find(params[:id])
		@updated = @order.update_attributes(order_params)
		
		respond_to do |format|
			format.js
		end
	end

	def destroy
		@order = Order.find(params[:id])
		@destroyed = @order.destroy

		respond_to do |format|
			format.js
		end
	end

	private

		def order_params
			params.require(:order).permit(:total, :payment_type, :customer_id, :event_id)
		end
end

app/helpers/orders_helper.rb
module OrdersHelper
	#show if cash or check was selectred
	def cash_selected(order)
		"selected" if order.payment_type == "cash"
	end

	def check_selected(order)
		"selected" if order.payment_type=="check"
	end

	def card_selected(order)
		"selected" if order.payment_type=="card"
	end
end

app/views/orders/_edit.html.erb
<div class='modal-overlay' id="payment-type-modal">
	<%= simple_form_for @order, remote: true do |f| %>
		<i class='fa fa-times exit-form'></i>

		<h1>How did the customer pay?</h1>

		<div class="sexy-divider"></div>

		<%= f.input :payment_type, as: :select, collection: ["cash", "check", "card"], label: false, input_html: {class: 'hide'} %>

		<div class="select-cash <%= cash_selected(@order) %>">Cash</div>

		<div class="select-check <%= check_selected(@order) %>">Check</div>

		<div class="select-card <%= card_selected(@order) %>">Card</div>

		<div style="clear:both;"></div>

		<%= f.submit nil, class: 'hide' %>
	<% end %>

	<div class="modal-overlay-footer">
		<%= link_to 'delete order', @order, remote: true, method: :delete, data: {confirm: "Sure you want to delete #{@order.customer.name}'s order?"}, class: 'delete-customer-link' %>
	</div>
</div>

app/views/orders/_open.html.erb
<div class="place-order place-order-<%= @order.id %>">
	<div class='sexy-divider'></div>

	<div class="order-vendor-list">
		<% @event.vendors.alphabetical.each_slice(4) do |slice| %>
			<div class='sexy-divider'></div>

			<div class="vendor-slice">
				<% slice.each do |vendor| %>
					<%= simple_form_for OrderItem.new, remote: true do |f| %>
						<%= f.hidden_field :vendor_id, value: vendor.id %>
						<%= f.hidden_field :customer_id, value: @customer.id %>
						<%= f.hidden_field :order_id, value: @order.id %>

						<%= button_tag(type: 'submit', class: 'order-vendor') do %>
							<%= vendor.name %>
						<% end %>
					<% end %>
				<% end %>
				
				<div style="clear:both;"></div>
			</div>
		<% end %>

		<div style='clear:both;'></div>

		<div class='sexy-divider'></div>
	</div>

	<div class='order-item-list'>
		<div class="checkout-total">
			<%= number_to_currency(@order.total, precision: (@order.total.round == @order.total) ? 0 : 2) %>
		</div>

		<%= render @order_items %>
	</div>

	<div style='clear:both;'></div>
</div>

app/views/orders/_order.html.erb
<div class='sexy-divider sexy-divider-<%= order.id %>'>
	<%= link_to raw("<i class='fa fa-cog'></i>"), edit_order_path(order), remote: true, class: 'edit-order-link' %> 
</div>

<%= link_to open_order_path(order), remote: true, class: "order order-#{order.id}" do %>
	<i class='fa fa-credit-card'></i>
	<span><%= order.customer.name %></span>
	
	<div style='clear:both;'></div>
<% end %>

app/views/orders/_order_modal.html.erb
order modal

app/views/orders/_payment_type.html.erb
<div class='modal-overlay' id="payment-type-modal">
	<%= simple_form_for @order, remote: true do |f| %>
		<%= link_to backtrack_order_path(@order), remote: true do %>
			<i class='fa fa-times exit-form'></i>
		<% end %>

		<h1>How did the customer pay?</h1>

		<div class="sexy-divider"></div>

		<%= f.input :payment_type, as: :select, collection: ["cash", "check", "card"], label: false, input_html: {class: 'hide'} %>

		<div class="select-cash">Cash</div>

		<div class="select-check">Check</div>

		<div class="select-card">Card</div>

		<div style="clear:both;"></div>

		<%= f.submit nil, class: 'hide' %>
	<% end %>
</div>

app/views/orders/backtrack.js.erb
<% if @destroyed %>
	$("#payment-type-modal").remove();
<% end %>

app/views/orders/create.js.erb
<% if @saved %>
	$("#dashboard-container").prepend("<%= j render 'orders/payment_type' %>");
<% end %>

app/views/orders/destroy.js.erb
<% if @destroyed %>
	//remove modal and everything related to deleted order
	$("#payment-type-modal").remove();
	$('.sexy-divider-<%= @order.id %>').remove();
	$(".order-<%= @order.id %>").remove();
	if($('.place-order-<%= @order.id %>')[0]){
		$(".place-order-<%= @order.id %>").remove();
	}
<% end %>

app/views/orders/edit.js.erb
$("#dashboard-container").prepend("<%= j render 'orders/edit' %>");

app/views/orders/index.html.erb
<% content_for :dashboard_content do %>
	<div data-toggle="modal" data-target="#changeModal" id="change-button">
		Calculate Change
	</div>
	<% if @orders.any? %>
		<table id="order-list">
			<tr>
				<th>Customer</th>
				<th>Total</th>
				<th>Donated</th>
				<th>Paid With</th>
				<th>Items</th>
				<th>Time</th>
				<th>Delete</th>
			</tr>
			<%= render @orders %>
		</table>

		<%= will_paginate @orders %>

		<div class="modal fade" id="changeModal">
		  <div class="modal-dialog">
		    <div class="modal-content">
		      <form>
					  <input type="text" ng-model="change.amount" placeholder="Input Cash Amount" id="payment-field">
					</form> 

					<span id="change-title">
						Change ($)
					</span>
					<div id="change-returned">
						{{change.amount- <%= @orders.recent_ones_first.first.total %> | number : 2 }}
					</div>
		    </div><!-- /.modal-content -->
		  </div><!-- /.modal-dialog -->
		</div><!-- /.modal -->
	<% else %>
		<div id="no-data">
			You don't have any orders yet!
		</div>
	<% end %>

	<script>
	$(document).ready(function(){
		$('#changeModal').on('shown.bs.modal', function(){
		  $('#payment-field').focus();
		});

		$(".select-payment-type").click(function(){
			$(this).children(".best_in_place").click();
		});
	});
	</script>
<% end %>

app/views/orders/load_order_price.js.erb
$("#orderModal .modal-dialog .modal-content").html("<%= j render 'orders/order_modal' %>"); 

app/views/orders/open.js.erb
if($('.place-order-<%= @order.id %>')[0]){
	//return to normal state
	$(".place-order").remove();
	$("#order-list .selected").removeClass('selected');
} else{
	//show form to place order
	if($(".place-order")[0]){
		$(".place-order").remove();
	}

	if($("#order-list .selected")[0]){
		$("#order-list .selected").removeClass('selected');
	}

	$(".order-<%= @order.id %>").after("<%= j render 'orders/open' %>");
	$(".order-<%= @order.id %>").addClass("selected");
}

app/views/orders/show.html.erb
<% content_for :dashboard_content do %>
	<div id="place-order-wrap">
		<% Vendor.alphabetical.where(participating: true).each do |vendor| %>
			<%= simple_form_for OrderItem.new, remote: true, html: {id: "order-item-form"} do |f| %>
				<%= f.input :vendor_id, input_html: {value: vendor.id, style: "visibility: hidden;"}, label: false %>
				<%= f.input :order_id, input_html: {value: @order.id, style: "visibility: hidden;"}, label: false %>
				<div id="place-order-item">
					<div id="order-item-vendor-<%= vendor.id %>">
						<%= f.submit "#{vendor.name}" %>
					</div>
				</div>
			<% end %>
		<% end %>
		<div style="clear:both;"></div>
	</div>

	<div id="place-order-wrap-two">
		<span id="name">
			<%= @order.customer.name %>
		</span>
		<br><br>
		<% if @order_items %>
			<% @order_items.each do |order_item| %>
				<div id="order-item-<%= order_item.id %>" class="input-order-item">
					<div class='order-item-vendor vendor-blue'>
						<%= order_item.vendor.name %>  <%= link_to "x", order_item, method: :delete, remote: true, id: "delete-order-item" %>
					</div>
					<div class="edit-order-item">
						<div id="quantity-field">
							<%= best_in_place order_item, :quantity %>
						</div>
						<div id="price-field">
							<span style="font-size:20px;">$</span><%= best_in_place order_item, :price %>
						</div>
					</div>
					<div style="clear:both;"></div>
				</div>
			<% end %>
		<% end %>
		<ul id="order-item-list">
		</ul>
	</div>
	<div id="checkout-btn-wrap">
		<%= link_to orders_path do %>
		<div id="checkout-btn" class="deactivated-button">
			Checkout
		</div>
		<% end %>
	</div>

	<% if @order_items.any? %>
		<script>
		$(document).ready(function(){
			$("#checkout-btn").removeClass("deactivated-button");
		});
		</script>
	<% end %>

	<script>
	$(document).ready(function(){
		$("#order-item-list").on("click", "#quantity-field", function(){
			$(this()
		});
	});
	</script>
<% end %>

app/views/orders/update.js.erb
<% if @updated %>
	$("#payment-type-modal").remove();

	if($('.place-order')[0]){
		$('.place-order').remove();
		if($('#customer-list .selected')[0]){
			$("#customer-list .selected").removeClass('selected');
		}

		if($('#order-list .selected')[0]){
			$("#order-list .selected").removeClass('selected');
		}
	}

	if($("#customer-search-field")[0]){
		$("#customer-search-field").val("").focus();
	}
<% end %>