config/routes.rb
AroundTheWorld::Application.routes.draw do
  get "events/index"
  #Static Pages
  root 'events#index'

  resources :events
  match '/events/:id/orders', to: 'events#event_orders', via: 'get', as: 'event_orders'
  match '/events/:id/vendors', to: 'events#event_vendors', via: 'get', as: 'event_vendors'
  match '/events/:id/analytics', to: 'events#event_analytics', via: 'get', as: 'event_analytics'

  resources :users
  match '/signup', to: 'users#new', via: 'get'

  resources :sessions, only: [:new, :create, :destroy]
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

  resources :vendors
  match '/vendors/:id/history', to: 'vendors#history', via: 'get'

  resources :customers do
    member do
      get 'place_order'
    end
  end

  resources :orders do
    member do
      get 'open'
      get 'backtrack'
    end
  end

  resources :order_items

  resources :analytics

  match '/home', to: 'static_pages#home', via: 'get'
end

app/models/vendor.rb
class Vendor < ActiveRecord::Base
	searchkick word_start: [:name]
	
	#validations
	validates :name, presence: true
	
	#relationships
	has_many :order_items
	belongs_to :event

	#scopes
	scope :alphabetical, -> {order('name ASC')}
	scope :recently, -> {order('created_at DESC')}

	def total_sold
		total = 0.0

		self.order_items.complete.each do |order_item|
			if order_item.order_id
				if self.tax
					total = total + 1.0875 * order_item.price * order_item.quantity
				else
					total = total+order_item.price*order_item.quantity
				end
			end
		end

		return total
	end
end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
	respond_to :html, :json

	def index
		@vendors = Vendor.recent_ones_first
	end

	def history
		@vendor = Vendor.find(params[:id])
		@order_items = OrderItem.where(vendor_id: @vendor)
	end

	def create
		@vendor = Vendor.new(vendor_params)
		@saved = @vendor.save

		respond_to do |format|
			format.js
		end
	end

	def edit
		@vendor = Vendor.find(params[:id])
	end

	def update
		@vendor = Vendor.find(params[:id])
		@updated = @vendor.update_attributes(vendor_params)
		respond_to do |format|
			format.js
		end
	end

	def destroy
		@vendor = Vendor.find(params[:id])
		@destroyed = @vendor.destroy

		respond_to do |format|
			format.js
		end
	end

	private

		def vendor_params
			params.require(:vendor).permit(:tax, :name, :email, :participating, :event_id, :user_id)
		end
end

app/helpers/vendors_helper.rb
module VendorsHelper
	#highlight vendor in analytics if total sold > 0
	def selected_row(vendor)
		'selected-row' if vendor.total_sold!=0.0
	end
end

app/views/vendors/_edit.html.erb
<div class='modal-overlay' id='edit-vendor-overlay'>
	<%= simple_form_for @vendor, remote: true do |f| %>
		<i class='fa fa-times exit-form'></i>

		<h1>Update Vendor</h1>

		<div class="sexy-divider"></div>

		<%= f.input :tax, label: "Charge tax" %>

		<div style='clear:both;'></div>
		
		<%= f.input :name, placeholder: 'Vendor Name', label: false, input_html: {class: 'default-input'} %>
		<%= f.input :email, placeholder: 'Vendor Email', label: false, input_html: {class: 'default-input'} %>

		<%= f.submit "Update Vendor", class: 'blue-button' %>
	<% end %>

	<div class="modal-overlay-footer">
		<%= link_to 'delete vendor', @vendor, remote: true, method: :delete, data: {confirm: "Sure you want to delete this vendor?"}, class: 'delete-vendor-link' %>
	</div>
</div>

app/views/vendors/_vendor.html.erb
<div class='sexy-divider sexy-divider-<%= vendor.id %>'>
	<%= link_to raw("<i class='fa fa-cog'></i>"), edit_vendor_path(vendor), remote: true, class: 'edit-vendor-link' %> 
</div>

<div class="vendor vendor-<%= vendor.id %>">
	<i class='fa fa-university'></i>
	<span><%= vendor.name %></span>
</div>

app/views/vendors/create.js.erb
<% if @saved %>
	//remove modal and show new vendor
	$('#vendor-overlay').hide();
	$('#new_vendor')[0].reset();
	$('#vendor-list').prepend("<%= j render @vendor %>");
<% end %>

app/views/vendors/destroy.js.erb
<% if @destroyed %>
	//remove modal and vendor
	$(".vendor-<%= @vendor.id %>").remove();
	$(".sexy-divider-<%= @vendor.id %>").remove();
	$("#edit-vendor-overlay").remove();
<% end %>

app/views/vendors/edit.js.erb
//load form to edit vendor
$("#dashboard-container").prepend("<%= j render 'vendors/edit' %>");
$("#edit-vendor-overlay #vendor_name").focus();

app/views/vendors/history.html.erb
<% content_for :dashboard_content do %>
	<div id="vendor-title">
		<%= @vendor.name %> <span style="color: rgba(110, 110, 110, 0.5);">Order History</span>
	</div>

	<% if @order_items %>
		<table id="vendor-list" style="margin-top:0px;">
			<tr>
				<th style="width: 50%;">Customer</th>
				<th style="width: 50%;">What'd he/she buy?</th>
			</tr>
		<% @order_items.each do |order_item| %>
			<% if order_item.price && order_item.quantity && order_item.price!=0 && order_item.quantity!=0 && order_item.order %>
			<tr>
				<td>
					<%= order_item.order.customer.name %>
				</td>
				<td>
					$<%= best_in_place order_item, :price %> x <%= best_in_place order_item, :quantity %>
					<% if @vendor.tax %>
						<% tax = order_item.price * order_item.quantity * 0.0875 %>
						+ <%= number_to_currency(tax, precision: (tax.round == tax) ? 0 : 2) %>
					<% end %>
				</td>
			</tr>
			<% end %>
		<% end %>
		</table>
	<% end %>
<% end %>

app/views/vendors/index.html.erb
<% content_for :dashboard_content do %>
	<%= simple_form_for Vendor.new, remote: true, html: {id: "vendor-form"} do |f| %>
		<%= f.input :name, label: false, input_html: {placeholder:"Name", id: "name-field", class: "stretch-field"} %>
		<%= f.submit "submit", style: "visibility: hidden;" %>
	<% end %>

	<div id="new-vendor-list">
	</div>

	<table id="vendor-list">
		<tr>
			<th>Name</th>
			<th>Total</th>
			<th>Donated</th>
			<th>Cash/Check</th>
			<th>Present</th>
			<th>Tax</th>
			<th>Other</th>
		</tr>
		<%= render @vendors %>
	</table>
<% end %>

app/views/vendors/update.js.erb
<% if @updated %>
	//remove modal to edit vendor
	$("#edit-vendor-overlay").remove();
	//replace vendor name
	$(".vendor-<%= @vendor.id %> span").html("<%= @vendor.name %>");
<% end %>