config/routes.rb
AroundTheWorld::Application.routes.draw do
  get "events/index"
  #Static Pages
  root 'events#index'

  resources :events
  match '/events/:id/orders', to: 'events#event_orders', via: 'get', as: 'event_orders'
  match '/events/:id/vendors', to: 'events#event_vendors', via: 'get', as: 'event_vendors'
  match '/events/:id/analytics', to: 'events#event_analytics', via: 'get', as: 'event_analytics'

  resources :users
  match '/signup', to: 'users#new', via: 'get'

  resources :sessions, only: [:new, :create, :destroy]
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

  resources :vendors
  match '/vendors/:id/history', to: 'vendors#history', via: 'get'

  resources :customers do
    member do
      get 'place_order'
    end
  end

  resources :orders do
    member do
      get 'open'
      get 'backtrack'
    end
  end

  resources :order_items

  resources :analytics

  match '/home', to: 'static_pages#home', via: 'get'
end

app/views/layouts/_bootstrap.html.erb
<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js"></script>

app/views/layouts/_dashboard.html.erb
<div id="dashboard-container">

	<div id="side-navbar">
		<div class="user-header">
			<span class='user-email'><%= truncate(current_user.email, length: 20) %></span>

			<%= link_to  signout_path, method: "delete" do %>
				<i class='fa fa-sign-out'></i>
			<% end %>
		</div>

		<div class="sexy-divider"></div>

		<%= render Event.recently %>

		<!-- button to load new event form -->
		<div class="add-event-button">
			+
		</div>
	</div>

	<!-- where the action happens -->

	<div id="main-container">
		<%= yield :dashboard_content %>
	</div>


	<!-- form to create new event -->
	<%= render 'events/new' %>
</div>

app/views/layouts/_fonts.html.erb
<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">

app/views/layouts/_ie_html5_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/ie_html5_shim' %>
  <%= render 'layouts/bootstrap' %>
  <%= render 'layouts/fonts' %>
</head>
<body>

<% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: "alert alert-#{key}") %>
<% end %>

<% if signed_in? %>
	<%= render 'layouts/dashboard' %>
<% else %>
	<%= yield %>
<% end %>

</body>
</html>